### ISSUE TITLE
the media rss parser is skipping the url string after the first ocuurence of "+" in the url.

### ISSUE THREAD

**Issue by hemant3370** [einmalfel/Earl#10]
https://archive.org/download/wieland_1606_librivox/format=64Kbps+MP3&ignore=x.mp3 is being returned as "https://archive.org/download/wieland_1606_librivox/format=64Kbps".

**Comment by einmalfel** [comment]
Hello, @hemant3370 !

Please, explain why did you close the issue. Problem turned out to be unrelated to Earl?

**Comment by hemant3370** [comment]
@einmalfel Yes it is related to textView skipping the string after the first occurence of "+" in the original string. Sorry.
