### ISSUE TITLE
Description and summary separation

### ISSUE THREAD

**Issue by mskarkala** [einmalfel/Earl#16]
Why the description and summary of an Item are not separated?
There is only one method to retrieve the description. What if I want for example to retrieve the summary instead?
Maybe they can be used for different purposes, like for example to have a "read more" button which will extend the summary into description.

**Comment by einmalfel** [comment]
Hello @mskarkala 
Item is a common interface for RSS items and Atom entries. RSS item has description, but doesn't have summary. For Atom its other way around. That's why I decided to make one getter for them.

There also is "summary" tag for items in Itunes extension. You can access it as RssItem.itunes.summary, while description is in RssItem.description

**Comment by mskarkala** [comment]
Hello @einmalfel. Thank you for your response.
Rss cannot have summary but Atom can have both summary and content. 
That is why I was wondering they cannot be accessed separately, by providing a getter for description/content and a getter for summary.
https://github.com/einmalfel/Earl/blob/master/earl/src/main/java/com/einmalfel/earl/AtomEntry.java#L199

**Comment by einmalfel** [comment]
@mskarkala 
Despite the fact that they have a common getter, they can be accessed separately, as they are both public fields of AtomEntry. E.g.:
Item firstItem = EarlParser.parseOrThrow(inputStream, 0).getItems().get(0);
AtomEntry entry = (AtomEntry) firstItem;
Log.d("", "Summary: " + entry.summary.value + ", content: " +  entry.content.value);

**Comment by mskarkala** [comment]
@einmalfel 
That can actually work for my case. Maybe you want to reconsider in the future separating the common getter.
Thank you for your quick response.

**Comment by einmalfel** [comment]
@mskarkala 
Happy to help,
> That can actually work for my case

that's how it's meant to be used. My intent was to provide high-level common interface (Feed and Item) for those who don't care about details, while all rss/atom-specific things are available as public final fields in RssFeed/RssItem/AtomFeed/AtomEntry POJO's
