### ISSUE TITLE
Parser failed to parse some tags

### ISSUE THREAD

**Issue by ghost** [einmalfel/Earl#3]
Hello,
I was trying to use the library and it seems to be failing to parse some fields, for example for this one: http://www.blogtalkradio.com/bobdavis/podcast
While the feed does have itunes tags, feed.itunes is null, and feed.items has size = 0.
This happens with all rss feeds from BlogTalkRadio

**Comment by einmalfel** [comment]
Hello, @khentek25 
Thanks for reporting the issue. I will look into it during this weekend.

**Comment by einmalfel** [comment]
@khentek25 fixed in version 1.0.1

**Comment by ghost** [comment]
Million thanks mate, I will try it out soon
