### ISSUE TITLE
Malformed date 2016-01-26T12:22:00Z

### ISSUE THREAD

**Issue by Scrounger** [einmalfel/Earl#5]
Hi,

cant parse the following date format:
W/Earl.Utils: Malformed date 2016-01-26T12:22:00Z

I get this error with this rss feed:
http://www.finanzen.net/rss/BASF-RSS-Feed

**Comment by einmalfel** [comment]
Hi, @Scrounger 

This date is in RFC3339 format, while RSS spec says dates should conform RFC 822.
I'm now implementing "tolerate parsing mode" which will workaround this issue along with other common RSS spec violations

**Comment by Scrounger** [comment]
Hi, @einmalfel,

thats the problem with the standards ;)
Thanks for implemneting this workaround!

**Comment by Scrounger** [comment]
@einmalfel 
Could you please implenent this?

**Comment by einmalfel** [comment]
@Scrounger I'm sorry, it's soo hard for me to find time for github projects nowdays :crying_cat_face: 
I'll try to carry this out during weekend

**Comment by noordawod** [comment]
This will be handled by my pull #12

**Comment by Scrounger** [comment]
I have seen that you merged this. Can you please release a new version?

**Comment by einmalfel** [comment]
Sure, will publish an update soon. Thanks for reminder!

**Comment by einmalfel** [comment]
Done
