### ISSUE TITLE
Bad parsing of timezone in RFC3339 dates

### ISSUE THREAD

**Issue by liminal** [einmalfel/Earl#8]
Error message is:
"Failed to parse RFC3339 string 2016-03-12T0936:25+00:00"

Note how there's a colon missing in the time part. I think it's caused by the timezone being prefixed with a + instead of a - which breaks an assumption made in Utils.java#L78-80

```
      //step one, split off the timezone.
      String firstPart = string.substring(0, string.lastIndexOf('-'));
      String secondPart = string.substring(string.lastIndexOf('-'));
```

**Comment by noordawod** [comment]
@liminal 

New changes have been pushed to address this problem. Could you try to fetch the master branch again and see if this problem still persists?

**Comment by liminal** [comment]
I honestly have no memory of what I was trying to do with this library so I can't replicate the problem but I'll close it since it looks fixed.
